name: Production Deployment
on:
  push:
    tags: ['*']
jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.REGISTRY_USERNAME || '~~TOKENAUTH~~' }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Run script
        run:
          werf converge
        env:
          WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
          WERF_ENV: production
          WERF_SET_DOMAIN: env.DOMAIN=iconicompany.ru
          WERF_REPO: registry.gitlab.com/${{ github.repository }}
          WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
